### ISSUE TITLE
Missing ',' in README example 

### ISSUE THREAD

**Issue by RELNO** [freeman-lab/control-panel#25]
In https://github.com/freeman-lab/control-panel#example

<img width="777" alt="screen shot 2018-08-13 at 10 10 29" src="https://user-images.githubusercontent.com/14296774/44037015-4c253292-9ee1-11e8-8c41-bb9fe529c5fa.png">

Should be: 
` {type: 'select', label: 'select one', options: ['option 1', 'option 2'], initial: 'option 1'} ,{type: 'multibox', label: 'check many', count: 3, initial: [true, false, true]}`

Thanks for a great tool!

**Comment by freeman-lab** [comment]
fixed by a PR, thanks for flagging!
